### ISSUE TITLE
you said that this code is in c in the blog post but it is in cpp 

### ISSUE THREAD

**Issue by dolev146** [covemountainsoftware/basicActiveObjectDemo#1]

**Comment by mattheweshleman** [comment]
hwLockCtrlService is a C based module, and it is the key module for this post and associated repo. The primary topic is centered around this module.

CppUTest is C++ based, but can (and was designed to) test either C or C++ code.
C++ is my preferred/default language, so other supporting code in the project is C++, sorry about any confusion.
